image: node:14

services:
  - postgres:13

variables:
  POSTGRES_DB: $DB_NAME
  POSTGRES_USER: $DB_USER
  POSTGRES_PASSWORD: $DB_PASSWORD
  DB_HOST: $DB_HOST
  DB_NAME: $DB_NAME
  DB_USER: $DB_USER
  DB_PASSWORD: $DB_PASSWORD

stages:
  - test
  - deploy

before_script:
  - npm install
  - npx sequelize-cli db:create
  - npx sequelize-cli db:migrate

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
  only:
    - master
